# Generated by Django 3.0.3 on 2020-02-24 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='A valid email address', max_length=254, null=True)),
                ('location', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(upload_to='', verbose_name='Profile Image')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('interests', models.ManyToManyField(to='users.Interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
