# Generated by Django 3.0.3 on 2020-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetails',
            name='thumbnail',
            field=models.ImageField(default='null', upload_to='', verbose_name='Group Picture'),
            preserve_default=False,
        ),
    ]
