# Generated by Django 3.0.3 on 2020-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createGroup', '0002_groupdetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='total_members',
            field=models.IntegerField(default=0),
        ),
    ]
