# Generated by Django 3.0.3 on 2020-03-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetAppGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Tanzania', 'TZ'), ('Uganda', 'UG'), ('Kenya', 'KN'), ('Nigeria', 'NG'), ('South Africa', 'RSA'), ('India', 'IND')], max_length=255)),
                ('desc', models.TextField(max_length=1000)),
                ('topics', models.ManyToManyField(to='group.Topics')),
            ],
        ),
    ]
