# Generated by Django 3.0.3 on 2020-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200310_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetappgroup',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
