# Generated by Django 3.0.3 on 2020-03-11 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizer'),
        ),
    ]
