# Generated by Django 3.0.3 on 2020-03-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200311_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
