# Generated by Django 3.0.3 on 2020-03-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_delete_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetappgroup',
            name='organizer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizer'),
            preserve_default=False,
        ),
    ]
