# Generated by Django 3.0.3 on 2020-03-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_meetappgroup_organizer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetappgroup',
            name='organizer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
